---

- hosts: home-pc

  roles:
    - role: frock81.pkgs
      tags: packages
      
    - role: frock81.gitconfig
      tags: git
      
    - role: frock81.keyboard
      tags: keyboard
      
    - role: frock81.dropbox
      tags: dropbox
