---
- hosts: home_pc
  roles:
    - role: frock81.ansible_bootstrap
      tags: boostrap

    # Review list of packages and urls before running playbook.
    - role: frock81.pkgs
      tags: pkgs

    # Better managed via Dotfiles
    - role: frock81.gitconfig
      tags: git

