---
# handlers file for frock81.tunnels
- name: systemd daemon reload
  command: systemctl daemon-reload
- name: restart tunnel service
  service:
    name: "{{ __tunnel_service_name }}"
    state: restarted