---
# Example:
#pkgs:
#  - name: apt-transport-https
#  - name: google-chrome-stable
#    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#  - name: sublime-text
#    key:
#      src: url
#      url: https://download.sublimetext.com/sublimehq-pub.gpg
#    repo: deb https://download.sublimetext.com/ apt/stable/
#  - name: spotify-client
#    key:
#      src: keyserver
#      id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
#      keyserver: keyserver.ubuntu.com
#    repo: deb http://repository.spotify.com stable non-free
#    proxy:
#      type: http
#      url: http://localhost:8123
#      location: repository.spotify.com
#  - name: spotify
#    src: snap
#  - name: zabbix-api
#    src: pip
pkgs: []
